FROM node:18.17.1-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

COPY . /app

WORKDIR /app/apps/web
RUN pnpm install --frozen-lockfile --force
# RUN pnpm dlx prisma generate

EXPOSE 3000

CMD [ "pnpm", "dev" ]
