FROM node:18.17.1-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && corepack prepare pnpm@8.6.12 --activate
RUN apt-get update -y && apt-get install -y openssl

WORKDIR /app

FROM base as dependencies

RUN pnpm add --global turbo

WORKDIR /app

COPY . /app/
RUN turbo prune --scope=web --scope=server --docker
RUN rm -rf /app/out/full/apps/web/node_modules
RUN rm -rf /app/out/full/apps/web/.next
RUN rm -rf /app/out/full/apps/server/node_modules

FROM base AS build
WORKDIR /app

COPY --from=dependencies /app/out/json/ /app/
COPY --from=dependencies /app/schema.prisma /app/schema.prisma
COPY --from=dependencies /app/tsconfig.json /app/tsconfig.json
RUN pnpm install --frozen-lockfile --force

COPY --from=dependencies /app/out/full/ .
RUN pnpm dlx prisma generate
RUN pnpm turbo run build --filter=web

FROM base AS web
WORKDIR /app

COPY --from=build /app/apps/web/.next/standalone /app/
COPY --from=build /app/apps/web/public /app/apps/web/public
COPY --from=build /app/apps/web/.next/static /app/apps/web/.next/static

WORKDIR /app/apps/web

EXPOSE 3000

CMD [ "node", "server.js" ]
