version: "3.1"

services:
    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - next-nest-trpc-db:/var/lib/mysql
        ports:
            - 3307:3306
        env_file:
            - ./docker-env/db.env

    adminer:
        image: adminer:4
        restart: always
        ports:
            - 7000:8080

volumes:
    next-nest-trpc-db:
