import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TRPCProvider from "./trpc/Provider";
import NextAuthProvider from "@web/app/_context/NextAuthProvider";
import { getServerSession } from "next-auth";
import MainNav from "@web/app/components/MainNav";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session = await getServerSession();

    return (
        <html lang="en">
            <body className={inter.className}>
                <NextAuthProvider session={session}>
                    <TRPCProvider>
                        <MainNav />
                        {children}
                    </TRPCProvider>
                </NextAuthProvider>
            </body>
        </html>
    );
}
